#  Problem set 4: k-NN, TF-IDF
#### Deadline: Tue, Feb 25th midnight

In [1]:
#importing packages
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Where are these texts coming from?

The data file texts.csv contains the texts you have to classify. It contains the following variables:
name name of the original file. It is usually author-name form and it should be fairly easy to find the
original text in most cases.
size size of the original text, in bytes
lines size of the original text, in lines
1
chunkid chunk id, from 1 and growing, see chunk. If you want to re-assemble the original texts, you just
have to put these next to each other in the order of chunkid.
chunk a page of text. It is not really a page, just 25 lines of text, whatever happened to be on those 25
lines.
Text chunks are just verbatim texts that may contain all kind of characters, including newlines. Note the
file is tab separated and uses quotes for strings.
Your task is to read all the texts, convert these to a) bag-of-words, and b) TF-IDF-s, and predict the
correct source using k-NN.

First, let's use bag-of-words (BOW) approach.

1. **Load the data. Print out a few lines of it to inspect it's structure.**
2. Inspect some of the texts. Note that chunkid 1 corresponds to the first page of the text.
3. List all the text sources listed in variable 'name'. How many different texts does the data contain?
When you feel you know the data well enough, it's time to split it into testing and validating parts.
Warning: start slow. The dataset contains 13,000 texts and 65,000 unique words. If you load in
everything, the BOW matrix takes approximately 8GB of RAM. I recommend to start with very small
datasets, say 10 pages for both training and validation. When your code works, start increasing the size.
Stop where it gets too slow, you don't have to run everything (it takes 18G RAM). But note that if you
drastically scale down the amount of data, you should also select only a few sources. Otherwise you may
have no examples from certain sources to compare to.

In [50]:
#load data
texts = pd.read_csv("texts.csv.bz2", sep = '\t')
#remove trailing new lines
texts.chunk = texts['chunk'].str.lstrip()

#data exploration
print(texts.head())
print()
print(texts.name.unique())
print('length: ' + str(len(texts.name.unique())))

                              name    size  lines  chunkid  \
0  balbulus-early-life-charlemagne  259062   4394        1
1  balbulus-early-life-charlemagne  259062   4394        2
2  balbulus-early-life-charlemagne  259062   4394        3
3  balbulus-early-life-charlemagne  259062   4394        4
4  balbulus-early-life-charlemagne  259062   4394        5

                                               chunk
0  Title: Early Lives of Charlemagne by Eginhard ...
1  The notes, keyed to line numbers in the source...
2  From a bronze statuette in the Musée Carnavale...
3  _A lui finit la dissolution de l’ancien\n     ...
4  public opinion in regard to the meaning of fal...

['balbulus-early-life-charlemagne' 'beesly-queen-elizabeth' 'bible'
 'carroll-alice-wonderland' 'chipman-earliest-electromagnetic-instruments'
 'cia-world-factbook-1992' 'eckstein-quintus-claudius'
 'fisher-quaker-colonies' 'gallienne-quest-of-golden-girl'
 'gordon-quiet-talks-crowned-christ' 'hardy-madding-crowd'
 'infiltrating-open-systems' 'kant-metaphysical-elements-ethics'
 'karn-snowflakes' 'milton-paradise-lost'
 'naval-academy-sound-military-decision' 'newsgroup'
 'paper-compact-hash-tables' 'paper-data-compression'
 'paper-logical-implementation-of-arithmetic'
 'paper-programming-by-example' 'paper-search-for-autonomy'
 'selected-polish-tales' 'shakespeare-as-you-like-it'
 'unamuno-tragic-sense-of-life' 'vaneeden-quest'
 'webster-early-european-history' 'why-speech-output'
 'workshop-proceedings']
length: 29

In [52]:
#first 2 rows 
ntexts = texts.groupby(['name']).apply(pd.DataFrame.sample, 2)

#split into training and testing data

#sorted values by chunkid so train and test wont have repeat titles
ntexts = ntexts.sort_values(by=['chunkid'])

#train = 48
#test = 10
training = ntexts.head(48)
val = ntexts.tail(10)

len(ntexts)

58

4. Now when you have created your training and testing sets, it is time to create the dictionary. See
the example code for python examples, there are many examples on the web about how to do it with
R (see text mining with R or text2vec package).
This process contains two steps: 1) create a dictionary of all your texts; 2) recode all the texts as
BOW vector. See the lecture notes for explanation about BOW.
Note you may want to feed in all your data, i.e. both training and validation data into the dictionary.
This ensures all words in your validation are represented in the dictionary.

In [2]:
#intialize vectorization
vectorizer = CountVectorizer(min_df=0)

In [53]:
#create dictionary
vec_fit = vectorizer.fit(ntexts.chunk)

5. Now you have all your (training and validation) texts in BOW form. This is great, we just transformed texts into (numeric) vectors! Now implement cosine similarity between these vectors.
Ensure you have read the lecture notes about cosine similarity. Write a function that takes in two
vectors, x and y, and returns the corresponding cosine similarity c(x,y). Test if c(x, x) = 1, test
also a few other vectors.

In [8]:
X = vec_fit.transform(train['chunk']).toarray()
y = vec_fit.transform(val['chunk']).toarray()

In [4]:
#cosine similarity function 
def cos_sim(x,y):
   return np.dot(x.T,y)/(np.linalg.norm(x) * np.linalg.norm(y))

In [ ]:
#testing multiple vectors
cos_sim(X[1,], X[1, ])
cos_sim(X[2,], X[1, ])
cos_sim(X[3,], X[1, ])
cos_sim(X[4,], X[1, ])
cos_sim(X[19,], X[1, ])

6. Finally, implement k-NN. I mean implement it yourself, don't use pre-existing libraries. I recommend
to do 1-NN first, and when this works to extend it to k-NN. You need an algorithm along these lines:

(a) Pick a validation case y (later you will loop over all of these).

(b) for each vector in the training set xi, compute the cosine similarity c(y, xi). Store this number,
and ensure you know which xi corresponds to each c value.

(c) Now order all the cosine similarities you just computed in an increasing order.

(d) Pick the k smallest c-s. These correspond to your k nearest neighbors! Ensure you know which
texts these are.

In [10]:
c = []
cos_sim(y[0, ], X[2, ])

for i in range(0, len(X)):
    c.append(cos_sim(y[0, ], X[i, ]))
    
centences = {'name' : train.name, 'cos_sim' : c}

centences = pd.DataFrame(data = centences)

centences= centences.sort_values(['cos_sim'])

centences.head()
#none of the top 5 match the name for 'y'

,,name,cos_sim
name,,,
paper-logical-implementation-of-arithmetic,8493,paper-logical-implementation-of-arithmetic,0.070067
paper-data-compression,8476,paper-data-compression,0.083017
shakespeare-as-you-like-it,9115,shakespeare-as-you-like-it,0.150798
paper-data-compression,8444,paper-data-compression,0.191987
selected-polish-tales,8556,selected-polish-tales,0.198148

7. Now you know your nearest neighbors. Organize a majority voting among them so you will learn
which text is the most popular among them. I recommend to create a frequency table and pick the
most common text source name based on this.
8. Compute accuracy (percentage of correct predictions). How good is your algorithm?

In [58]:
#knn algorithm
#returns a table including n neighbors for each validation case with cosine-similarity scores
def getNeighbors(training, validation, k, test):
    freq_table = {'val_name' : [] , 'train_name' : [], 'cos_sim' : []}
    X = vec_fit.transform(training[test]).toarray()
    y = vec_fit.transform(validation[test]).toarray()
    for i in range(0, len(y)):
        for j in range(0, len(X)):
            freq_table['val_name'].append(validation.iloc[i]['name'])
            freq_table['train_name'].append(training.iloc[j]['name'])
            freq_table['cos_sim'].append(cos_sim(y[i, ], X[j, ]))
    freq_table = pd.DataFrame(data = freq_table)
    freq_table = freq_table.groupby(['val_name']).apply(pd.DataFrame.sort_values, 'cos_sim')
    freq_table = freq_table.groupby(['val_name']).head(k)
    return freq_table

In [48]:
#finds matches between name/fresh columns
def matching(df, col1, col2):
    matches = []
    for i in range(0, len(df)):
        if df.iloc[i][col1] == df.iloc[i][col2]:
            matches.append(1)
        else:
            matches.append(0)
    return matches

In [47]:
#finds accuracies for each validation case
def listAcc(matches, k):
    accuracies = []
    i = 0
    while i < len(matches):
        ival = np.mean(matches[i : i+k])
        accuracies.append(np.mean(ival))
        i = i + k
    return accuracies

In [59]:
n = getNeighbors(training, val, 5 , 'name')
n_matches = matching(n, 'train_name', 'val_name')
print(listAcc(n_matches, 5))
print('accuracy score:' + str(np.mean(listAcc(n_matches, 5))))
n['matches'] = n_matches
n

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
accuracy score:0.0

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: 'val_name' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version

                                                          val_name  \
val_name
bible                          96                            bible
                               121                           bible
                               122                           bible
                               123                           bible
                               126                           bible
cia-world-factbook-1992        432         cia-world-factbook-1992
                               458         cia-world-factbook-1992
                               459         cia-world-factbook-1992
                               461         cia-world-factbook-1992
                               462         cia-world-factbook-1992
eckstein-quintus-claudius      192       eckstein-quintus-claudius
                               217       eckstein-quintus-claudius
                               218       eckstein-quintus-claudius
                               219       eckstein-quintus-claudius
                               221       eckstein-quintus-claudius
milton-paradise-lost           144            milton-paradise-lost
                               170            milton-paradise-lost
                               171            milton-paradise-lost
                               173            milton-paradise-lost
                               174            milton-paradise-lost
newsgroup                      48                        newsgroup
                               49                        newsgroup
                               50                        newsgroup
                               51                        newsgroup
                               52                        newsgroup
unamuno-tragic-sense-of-life   240    unamuno-tragic-sense-of-life
                               264    unamuno-tragic-sense-of-life
                               265    unamuno-tragic-sense-of-life
                               266    unamuno-tragic-sense-of-life
                               267    unamuno-tragic-sense-of-life
vaneeden-quest                 336                  vaneeden-quest
                               337                  vaneeden-quest
                               338                  vaneeden-quest
                               339                  vaneeden-quest
                               340                  vaneeden-quest
webster-early-european-history 0    webster-early-european-history
                               402  webster-early-european-history
                               401  webster-early-european-history
                               400  webster-early-european-history
                               398  webster-early-european-history
why-speech-output              288               why-speech-output
                               314               why-speech-output
                               315               why-speech-output
                               317               why-speech-output
                               318               why-speech-output

                                                                    train_name  \
val_name
bible                          96                    paper-search-for-autonomy
                               121                   infiltrating-open-systems
                               122                      beesly-queen-elizabeth
                               123           gordon-quiet-talks-crowned-christ
                               126             balbulus-early-life-charlemagne
cia-world-factbook-1992        432                   paper-search-for-autonomy
                               458                      beesly-queen-elizabeth
                               459           gordon-quiet-talks-crowned-christ
                               461                                       bible
                               462             balbulus-early-life-charlemagne
eckstein-quintus-claudius      192                   paper-search-for-autonomy
                               217                   infiltrating-open-systems
                               218                      beesly-queen-elizabeth
                               219           gordon-quiet-talks-crowned-christ
                               221                                       bible
milton-paradise-lost           144                   paper-search-for-autonomy
                               170                      beesly-queen-elizabeth
                               171           gordon-quiet-talks-crowned-christ
                               173                                       bible
                               174             balbulus-early-life-charlemagne
newsgroup                      48                    paper-search-for-autonomy
                               49   paper-logical-implementation-of-arithmetic
                               50                   shakespeare-as-you-like-it
                               51                       paper-data-compression
                               52                 paper-programming-by-example
unamuno-tragic-sense-of-life   240                   paper-search-for-autonomy
                               264                    carroll-alice-wonderland
                               265                   infiltrating-open-systems
                               266                      beesly-queen-elizabeth
                               267           gordon-quiet-talks-crowned-christ
vaneeden-quest                 336                   paper-search-for-autonomy
                               337  paper-logical-implementation-of-arithmetic
                               338                  shakespeare-as-you-like-it
                               339                      paper-data-compression
                               340                paper-programming-by-example
webster-early-european-history 0                     paper-search-for-autonomy
                               402                   infiltrating-open-systems
                               401       naval-academy-sound-military-decision
                               400           kant-metaphysical-elements-ethics
                               398                      fisher-quaker-colonies
why-speech-output              288                   paper-search-for-autonomy
                               314                      beesly-queen-elizabeth
                               315           gordon-quiet-talks-crowned-christ
                               317                                       bible
                               318             balbulus-early-life-charlemagne

                                    cos_sim  matches
val_name
bible                          96       0.0        0
                               121      0.0        0
                               122      0.0        0
                               123      0.0        0
                               126      0.0        0
cia-world-factbook-1992        432      0.0        0
                               458      0.0        0
                               459      0.0        0
                               461      0.0        0
                               462      0.0        0
eckstein-quintus-claudius      192      0.0        0
                               217      0.0        0
                               218      0.0        0
                               219      0.0        0
                               221      0.0        0
milton-paradise-lost           144      0.0        0
                               170      0.0        0
                               171      0.0        0
                               173      0.0        0
                               174      0.0        0
newsgroup                      48       NaN        0
                               49       NaN        0
                               50       NaN        0
                               51       NaN        0
                               52       NaN        0
unamuno-tragic-sense-of-life   240      0.0        0
                               264      0.0        0
                               265      0.0        0
                               266      0.0        0
                               267      0.0        0
vaneeden-quest                 336      NaN        0
                               337      NaN        0
                               338      NaN        0
                               339      NaN        0
                               340      NaN        0
webster-early-european-history 0        0.0        0
                               402      0.0        0
                               401      0.0        0
                               400      0.0        0
                               398      0.0        0
why-speech-output              288      0.0        0
                               314      0.0        0
                               315      0.0        0
                               317      0.0        0
                               318      0.0        0

Now it is time to start increasing the training and testing sets. I repeat: go slow. Training set of 1000
and testing set 100 should be fine. Go further if your memory and speed permit. When you have found
the limits you don't want to exceed (say, 5 mins for the run), it is time to play with k.
9. compare different k values. 1, 5, 25 are a good choice. Which k gives you the best performance?
What is your highest accuracy?

In [66]:
#samples 100 rows
ntexts = texts.sample(100)
training = ntexts.sample(frac = 0.8, random_state = 1)
val = ntexts.sample(frac = 0.2, random_state = 1)

In [67]:
# k = 1
n = getNeighbors(training, val, 1 , 'name')
n_matches = matching(n, 'train_name', 'val_name')
print(listAcc(n_matches, 1))
print('accuracy score:' + str(np.mean(listAcc(n_matches, 1))))
n['matches'] = n_matches
n

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
accuracy score:0.0

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: 'val_name' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version

,,val_name,train_name,cos_sim,matches
val_name,,,,,
beesly-queen-elizabeth,720,beesly-queen-elizabeth,unamuno-tragic-sense-of-life,0.0,0
cia-world-factbook-1992,320,cia-world-factbook-1992,unamuno-tragic-sense-of-life,0.0,0
eckstein-quintus-claudius,800,eckstein-quintus-claudius,unamuno-tragic-sense-of-life,0.0,0
gallienne-quest-of-golden-girl,433,gallienne-quest-of-golden-girl,naval-academy-sound-military-decision,0.0,0
gordon-quiet-talks-crowned-christ,480,gordon-quiet-talks-crowned-christ,unamuno-tragic-sense-of-life,0.0,0
hardy-madding-crowd,240,hardy-madding-crowd,unamuno-tragic-sense-of-life,NaN,0
milton-paradise-lost,80,milton-paradise-lost,unamuno-tragic-sense-of-life,0.0,0
naval-academy-sound-military-decision,560,naval-academy-sound-military-decision,unamuno-tragic-sense-of-life,0.0,0
newsgroup,1040,newsgroup,unamuno-tragic-sense-of-life,NaN,0
unamuno-tragic-sense-of-life,1153,unamuno-tragic-sense-of-life,naval-academy-sound-military-decision,0.0,0
vaneeden-quest,1440,vaneeden-quest,unamuno-tragic-sense-of-life,NaN,0
webster-early-european-history,1200,webster-early-european-history,unamuno-tragic-sense-of-life,0.0,0
why-speech-output,880,why-speech-output,unamuno-tragic-sense-of-life,0.0,0

In [68]:
# k = 5
n = getNeighbors(training, val, 5 , 'name')
n_matches = matching(n, 'train_name', 'val_name')
print(listAcc(n_matches, 5))
print('accuracy score:' + str(np.mean(listAcc(n_matches, 5))))
n['matches'] = n_matches
n

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until

[0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
accuracy score:0.015384615384615385

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: 'val_name' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version

                                                                         val_name  \
val_name
beesly-queen-elizabeth                720                  beesly-queen-elizabeth
                                      757                  beesly-queen-elizabeth
                                      758                  beesly-queen-elizabeth
                                      760                  beesly-queen-elizabeth
                                      761                  beesly-queen-elizabeth
cia-world-factbook-1992               320                 cia-world-factbook-1992
                                      1305                cia-world-factbook-1992
                                      1306                cia-world-factbook-1992
                                      1308                cia-world-factbook-1992
                                      1309                cia-world-factbook-1992
eckstein-quintus-claudius             800               eckstein-quintus-claudius
                                      840               eckstein-quintus-claudius
                                      841               eckstein-quintus-claudius
                                      842               eckstein-quintus-claudius
                                      844               eckstein-quintus-claudius
gallienne-quest-of-golden-girl        433          gallienne-quest-of-golden-girl
                                      474          gallienne-quest-of-golden-girl
                                      478          gallienne-quest-of-golden-girl
                                      437          gallienne-quest-of-golden-girl
                                      438          gallienne-quest-of-golden-girl
gordon-quiet-talks-crowned-christ     480       gordon-quiet-talks-crowned-christ
                                      520       gordon-quiet-talks-crowned-christ
                                      521       gordon-quiet-talks-crowned-christ
                                      522       gordon-quiet-talks-crowned-christ
                                      524       gordon-quiet-talks-crowned-christ
hardy-madding-crowd                   240                     hardy-madding-crowd
                                      241                     hardy-madding-crowd
                                      242                     hardy-madding-crowd
                                      243                     hardy-madding-crowd
                                      244                     hardy-madding-crowd
...                                                                           ...
naval-academy-sound-military-decision 560   naval-academy-sound-military-decision
                                      670   naval-academy-sound-military-decision
                                      669   naval-academy-sound-military-decision
                                      668   naval-academy-sound-military-decision
                                      667   naval-academy-sound-military-decision
newsgroup                             1040                              newsgroup
                                      1041                              newsgroup
                                      1042                              newsgroup
                                      1043                              newsgroup
                                      1044                              newsgroup
unamuno-tragic-sense-of-life          1153           unamuno-tragic-sense-of-life
                                      1171           unamuno-tragic-sense-of-life
                                      1172           unamuno-tragic-sense-of-life
                                      1173           unamuno-tragic-sense-of-life
                                      1176           unamuno-tragic-sense-of-life
vaneeden-quest                        1440                         vaneeden-quest
                                      1441                         vaneeden-quest
                                      1442                         vaneeden-quest
                                      1443                         vaneeden-quest
                                      1444                         vaneeden-quest
webster-early-european-history        1200         webster-early-european-history
                                      1237         webster-early-european-history
                                      1238         webster-early-european-history
                                      1240         webster-early-european-history
                                      1242         webster-early-european-history
why-speech-output                     880                       why-speech-output
                                      920                       why-speech-output
                                      921                       why-speech-output
                                      922                       why-speech-output
                                      924                       why-speech-output

                                                                       train_name  \
val_name
beesly-queen-elizabeth                720            unamuno-tragic-sense-of-life
                                      757                 cia-world-factbook-1992
                                      758                 cia-world-factbook-1992
                                      760                    workshop-proceedings
                                      761          webster-early-european-history
cia-world-factbook-1992               320            unamuno-tragic-sense-of-life
                                      1305                                  bible
                                      1306                                  bible
                                      1308                   workshop-proceedings
                                      1309                   workshop-proceedings
eckstein-quintus-claudius             800            unamuno-tragic-sense-of-life
                                      840                    workshop-proceedings
                                      841          webster-early-european-history
                                      842                                   bible
                                      844                                   bible
gallienne-quest-of-golden-girl        433   naval-academy-sound-military-decision
                                      474                 cia-world-factbook-1992
                                      478                 cia-world-factbook-1992
                                      437                 cia-world-factbook-1992
                                      438                 cia-world-factbook-1992
gordon-quiet-talks-crowned-christ     480            unamuno-tragic-sense-of-life
                                      520                    workshop-proceedings
                                      521          webster-early-european-history
                                      522                                   bible
                                      524                                   bible
hardy-madding-crowd                   240            unamuno-tragic-sense-of-life
                                      241                    milton-paradise-lost
                                      242                    milton-paradise-lost
                                      243                     hardy-madding-crowd
                                      244                 cia-world-factbook-1992
...                                                                           ...
naval-academy-sound-military-decision 560            unamuno-tragic-sense-of-life
                                      670          webster-early-european-history
                                      669                    workshop-proceedings
                                      668                    workshop-proceedings
                                      667                 cia-world-factbook-1992
newsgroup                             1040           unamuno-tragic-sense-of-life
                                      1041                   milton-paradise-lost
                                      1042                   milton-paradise-lost
                                      1043                    hardy-madding-crowd
                                      1044                cia-world-factbook-1992
unamuno-tragic-sense-of-life          1153  naval-academy-sound-military-decision
                                      1171                 beesly-queen-elizabeth
                                      1172                cia-world-factbook-1992
                                      1173                                  bible
                                      1176                   workshop-proceedings
vaneeden-quest                        1440           unamuno-tragic-sense-of-life
                                      1441                   milton-paradise-lost
                                      1442                   milton-paradise-lost
                                      1443                    hardy-madding-crowd
                                      1444                cia-world-factbook-1992
webster-early-european-history        1200           unamuno-tragic-sense-of-life
                                      1237                cia-world-factbook-1992
                                      1238                cia-world-factbook-1992
                                      1240                   workshop-proceedings
                                      1242                                  bible
why-speech-output                     880            unamuno-tragic-sense-of-life
                                      920                    workshop-proceedings
                                      921          webster-early-european-history
                                      922                                   bible
                                      924                                   bible

                                            cos_sim  matches
val_name
beesly-queen-elizabeth                720       0.0        0
                                      757       0.0        0
                                      758       0.0        0
                                      760       0.0        0
                                      761       0.0        0
cia-world-factbook-1992               320       0.0        0
                                      1305      0.0        0
                                      1306      0.0        0
                                      1308      0.0        0
                                      1309      0.0        0
eckstein-quintus-claudius             800       0.0        0
                                      840       0.0        0
                                      841       0.0        0
                                      842       0.0        0
                                      844       0.0        0
gallienne-quest-of-golden-girl        433       0.0        0
                                      474       0.0        0
                                      478       0.0        0
                                      437       0.0        0
                                      438       0.0        0
gordon-quiet-talks-crowned-christ     480       0.0        0
                                      520       0.0        0
                                      521       0.0        0
                                      522       0.0        0
                                      524       0.0        0
hardy-madding-crowd                   240       NaN        0
                                      241       NaN        0
                                      242       NaN        0
                                      243       NaN        1
                                      244       NaN        0
...                                             ...      ...
naval-academy-sound-military-decision 560       0.0        0
                                      670       0.0        0
                                      669       0.0        0
                                      668       0.0        0
                                      667       0.0        0
newsgroup                             1040      NaN        0
                                      1041      NaN        0
                                      1042      NaN        0
                                      1043      NaN        0
                                      1044      NaN        0
unamuno-tragic-sense-of-life          1153      0.0        0
                                      1171      0.0        0
                                      1172      0.0        0
                                      1173      0.0        0
                                      1176      0.0        0
vaneeden-quest                        1440      NaN        0
                                      1441      NaN        0
                                      1442      NaN        0
                                      1443      NaN        0
                                      1444      NaN        0
webster-early-european-history        1200      0.0        0
                                      1237      0.0        0
                                      1238      0.0        0
                                      1240      0.0        0
                                      1242      0.0        0
why-speech-output                     880       0.0        0
                                      920       0.0        0
                                      921       0.0        0
                                      922       0.0        0
                                      924       0.0        0

[65 rows x 4 columns]

In [69]:
# k = 25
n = getNeighbors(training, val, 25 , 'name')
n_matches = matching(n, 'train_name', 'val_name')
print(listAcc(n_matches, 25))
print('accuracy score:' + str(np.mean(listAcc(n_matches, 25))))
n['matches'] = n_matches
n

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: 'val_name' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version

[0.0, 0.0, 0.0, 0.0, 0.0, 0.04, 0.0, 0.0, 0.04, 0.0, 0.08, 0.0, 0.0]
accuracy score:0.012307692307692308

                                                           val_name  \
val_name
beesly-queen-elizabeth         720           beesly-queen-elizabeth
                               757           beesly-queen-elizabeth
                               758           beesly-queen-elizabeth
                               760           beesly-queen-elizabeth
                               761           beesly-queen-elizabeth
                               762           beesly-queen-elizabeth
                               764           beesly-queen-elizabeth
                               766           beesly-queen-elizabeth
                               767           beesly-queen-elizabeth
                               768           beesly-queen-elizabeth
                               769           beesly-queen-elizabeth
                               772           beesly-queen-elizabeth
                               773           beesly-queen-elizabeth
                               776           beesly-queen-elizabeth
                               777           beesly-queen-elizabeth
                               778           beesly-queen-elizabeth
                               779           beesly-queen-elizabeth
                               786           beesly-queen-elizabeth
                               787           beesly-queen-elizabeth
                               789           beesly-queen-elizabeth
                               790           beesly-queen-elizabeth
                               791           beesly-queen-elizabeth
                               794           beesly-queen-elizabeth
                               795           beesly-queen-elizabeth
                               796           beesly-queen-elizabeth
cia-world-factbook-1992        320          cia-world-factbook-1992
                               1305         cia-world-factbook-1992
                               1306         cia-world-factbook-1992
                               1308         cia-world-factbook-1992
                               1309         cia-world-factbook-1992
...                                                             ...
webster-early-european-history 1270  webster-early-european-history
                               1271  webster-early-european-history
                               1274  webster-early-european-history
                               1275  webster-early-european-history
                               1276  webster-early-european-history
why-speech-output              880                why-speech-output
                               920                why-speech-output
                               921                why-speech-output
                               922                why-speech-output
                               924                why-speech-output
                               925                why-speech-output
                               926                why-speech-output
                               927                why-speech-output
                               928                why-speech-output
                               929                why-speech-output
                               930                why-speech-output
                               931                why-speech-output
                               932                why-speech-output
                               918                why-speech-output
                               933                why-speech-output
                               937                why-speech-output
                               938                why-speech-output
                               939                why-speech-output
                               946                why-speech-output
                               947                why-speech-output
                               949                why-speech-output
                               950                why-speech-output
                               951                why-speech-output
                               954                why-speech-output
                               955                why-speech-output

                                                         train_name  cos_sim  \
val_name
beesly-queen-elizabeth         720     unamuno-tragic-sense-of-life      0.0
                               757          cia-world-factbook-1992      0.0
                               758          cia-world-factbook-1992      0.0
                               760             workshop-proceedings      0.0
                               761   webster-early-european-history      0.0
                               762                            bible      0.0
                               764                            bible      0.0
                               766                            bible      0.0
                               767            selected-polish-tales      0.0
                               768         carroll-alice-wonderland      0.0
                               769   webster-early-european-history      0.0
                               772          cia-world-factbook-1992      0.0
                               773                            bible      0.0
                               776             workshop-proceedings      0.0
                               777            selected-polish-tales      0.0
                               778          cia-world-factbook-1992      0.0
                               779          cia-world-factbook-1992      0.0
                               786                            bible      0.0
                               787   webster-early-european-history      0.0
                               789     unamuno-tragic-sense-of-life      0.0
                               790         carroll-alice-wonderland      0.0
                               791          cia-world-factbook-1992      0.0
                               794          cia-world-factbook-1992      0.0
                               795          cia-world-factbook-1992      0.0
                               796     unamuno-tragic-sense-of-life      0.0
cia-world-factbook-1992        320     unamuno-tragic-sense-of-life      0.0
                               1305                           bible      0.0
                               1306                           bible      0.0
                               1308            workshop-proceedings      0.0
                               1309            workshop-proceedings      0.0
...                                                             ...      ...
webster-early-european-history 1270        carroll-alice-wonderland      0.0
                               1271         cia-world-factbook-1992      0.0
                               1274         cia-world-factbook-1992      0.0
                               1275         cia-world-factbook-1992      0.0
                               1276    unamuno-tragic-sense-of-life      0.0
why-speech-output              880     unamuno-tragic-sense-of-life      0.0
                               920             workshop-proceedings      0.0
                               921   webster-early-european-history      0.0
                               922                            bible      0.0
                               924                            bible      0.0
                               925           beesly-queen-elizabeth      0.0
                               926                            bible      0.0
                               927            selected-polish-tales      0.0
                               928         carroll-alice-wonderland      0.0
                               929   webster-early-european-history      0.0
                               930           beesly-queen-elizabeth      0.0
                               931           beesly-queen-elizabeth      0.0
                               932          cia-world-factbook-1992      0.0
                               918          cia-world-factbook-1992      0.0
                               933                            bible      0.0
                               937            selected-polish-tales      0.0
                               938          cia-world-factbook-1992      0.0
                               939          cia-world-factbook-1992      0.0
                               946                            bible      0.0
                               947   webster-early-european-history      0.0
                               949     unamuno-tragic-sense-of-life      0.0
                               950         carroll-alice-wonderland      0.0
                               951          cia-world-factbook-1992      0.0
                               954          cia-world-factbook-1992      0.0
                               955          cia-world-factbook-1992      0.0

                                     matches
val_name
beesly-queen-elizabeth         720         0
                               757         0
                               758         0
                               760         0
                               761         0
                               762         0
                               764         0
                               766         0
                               767         0
                               768         0
                               769         0
                               772         0
                               773         0
                               776         0
                               777         0
                               778         0
                               779         0
                               786         0
                               787         0
                               789         0
                               790         0
                               791         0
                               794         0
                               795         0
                               796         0
cia-world-factbook-1992        320         0
                               1305        0
                               1306        0
                               1308        0
                               1309        0
...                                      ...
webster-early-european-history 1270        0
                               1271        0
                               1274        0
                               1275        0
                               1276        0
why-speech-output              880         0
                               920         0
                               921         0
                               922         0
                               924         0
                               925         0
                               926         0
                               927         0
                               928         0
                               929         0
                               930         0
                               931         0
                               932         0
                               918         0
                               933         0
                               937         0
                               938         0
                               939         0
                               946         0
                               947         0
                               949         0
                               950         0
                               951         0
                               954         0
                               955         0

[325 rows x 4 columns]

In [38]:
print(listAccuracies(neighbors3))
print('accuracy score:' + str(np.mean(listAccuracies(neighbors3))))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04, 0.0, 0.04, 0.0, 0.0, 0.0, 0.04, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
accuracy score:0.004137931034482759

k = 25 gives me the best performance

##  TF-IDF

BOW is great but could be even greater. Can we get a better result using TF-IDF? TF-IDF is simply a
way how to weigh the word frequency in a more informative way.
1. implement TF-IDF transformation. Note: implement it yourself, don't rely on existing libraries!
This involves manipulating your training and validation data matrices, nothing else needs to be
done. Example will be given in the notes.
2. Now ensure that your cosine similarity you implemented earlier also works for vectors in TF-IDF
form. It should, without any modifications, if you implemented in well.
3. Run your k-NN with cosine similarity algorithm again, using several k values, like 1,5,25. The
algorithm should not need any modifications.

In [ ]:
## Implement TF-IDF.
## the tf part is just 1 + log-ing the counts
## the idf part is slighly more complex: you need counts of all words
## use something like X.sum(axis = 0) on numpy array to sum the
## elements columnwise.  Now you can easily calculate the
## IDF transform of the counts.
##
## Finally, ensure that tf and idf are multiplied correctly:
## the former is a matrix, the latter a vector.  It should be
## broadcasted automatically, but please check if it is.

In [3]:
#tf equation
def tf(value): 
    return (np.log(1 + value))

#idf part
def idf(X):
    return (X.sum(axis = 0))

In [71]:
def getNeighbors_tfidf(training, validation, k, test):
    freq_table = {'val_name' : [] , 'train_name' : [], 'cos_sim' : []}
    X = vec_fit.transform(training[test]).toarray()
    y = vec_fit.transform(validation[test]).toarray()
    #tf-idf part
    X = tf(X) * idf(X)
    y = tf(y) * idf(y)

    for i in range(0, len(y)):
        for j in range(0, len(X)):
            freq_table['val_name'].append(validation.iloc[i]['name'])
            freq_table['train_name'].append(training.iloc[j]['name'])
            freq_table['cos_sim'].append(cos_sim(y[i, ], X[j, ]))
    freq_table = pd.DataFrame(data = freq_table)
    freq_table = freq_table.groupby(['val_name']).apply(pd.DataFrame.sort_values, 'cos_sim')
    freq_table = freq_table.groupby(['val_name']).head(k)
    return freq_table

In [72]:
# k = 1
n = getNeighbors_tfidf(training, val, 1 , 'name')
n_matches = matching(n, 'train_name', 'val_name')
print(listAcc(n_matches, 1))
print('accuracy score:' + str(np.mean(listAcc(n_matches, 1))))
n['matches'] = n_matches
n

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
accuracy score:0.0

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: 'val_name' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version
  app.launch_new_instance()

,,val_name,train_name,cos_sim,matches
val_name,,,,,
beesly-queen-elizabeth,720,beesly-queen-elizabeth,unamuno-tragic-sense-of-life,0.0,0
cia-world-factbook-1992,320,cia-world-factbook-1992,unamuno-tragic-sense-of-life,0.0,0
eckstein-quintus-claudius,800,eckstein-quintus-claudius,unamuno-tragic-sense-of-life,0.0,0
gallienne-quest-of-golden-girl,433,gallienne-quest-of-golden-girl,naval-academy-sound-military-decision,0.0,0
gordon-quiet-talks-crowned-christ,480,gordon-quiet-talks-crowned-christ,unamuno-tragic-sense-of-life,0.0,0
hardy-madding-crowd,240,hardy-madding-crowd,unamuno-tragic-sense-of-life,NaN,0
milton-paradise-lost,80,milton-paradise-lost,unamuno-tragic-sense-of-life,0.0,0
naval-academy-sound-military-decision,560,naval-academy-sound-military-decision,unamuno-tragic-sense-of-life,0.0,0
newsgroup,1040,newsgroup,unamuno-tragic-sense-of-life,NaN,0
unamuno-tragic-sense-of-life,1153,unamuno-tragic-sense-of-life,naval-academy-sound-military-decision,0.0,0
vaneeden-quest,1440,vaneeden-quest,unamuno-tragic-sense-of-life,NaN,0
webster-early-european-history,1200,webster-early-european-history,unamuno-tragic-sense-of-life,0.0,0
why-speech-output,880,why-speech-output,unamuno-tragic-sense-of-life,0.0,0

In [73]:
# k = 5
n = getNeighbors_tfidf(training, val, 5 , 'name')
n_matches = matching(n, 'train_name', 'val_name')
print(listAcc(n_matches, 5))
print('accuracy score:' + str(np.mean(listAcc(n_matches, 5))))
n['matches'] = n_matches
n

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until

[0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
accuracy score:0.015384615384615385

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: 'val_name' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version
  app.launch_new_instance()

                                                                         val_name  \
val_name
beesly-queen-elizabeth                720                  beesly-queen-elizabeth
                                      757                  beesly-queen-elizabeth
                                      758                  beesly-queen-elizabeth
                                      760                  beesly-queen-elizabeth
                                      761                  beesly-queen-elizabeth
cia-world-factbook-1992               320                 cia-world-factbook-1992
                                      1305                cia-world-factbook-1992
                                      1306                cia-world-factbook-1992
                                      1308                cia-world-factbook-1992
                                      1309                cia-world-factbook-1992
eckstein-quintus-claudius             800               eckstein-quintus-claudius
                                      840               eckstein-quintus-claudius
                                      841               eckstein-quintus-claudius
                                      842               eckstein-quintus-claudius
                                      844               eckstein-quintus-claudius
gallienne-quest-of-golden-girl        433          gallienne-quest-of-golden-girl
                                      474          gallienne-quest-of-golden-girl
                                      478          gallienne-quest-of-golden-girl
                                      437          gallienne-quest-of-golden-girl
                                      438          gallienne-quest-of-golden-girl
gordon-quiet-talks-crowned-christ     480       gordon-quiet-talks-crowned-christ
                                      520       gordon-quiet-talks-crowned-christ
                                      521       gordon-quiet-talks-crowned-christ
                                      522       gordon-quiet-talks-crowned-christ
                                      524       gordon-quiet-talks-crowned-christ
hardy-madding-crowd                   240                     hardy-madding-crowd
                                      241                     hardy-madding-crowd
                                      242                     hardy-madding-crowd
                                      243                     hardy-madding-crowd
                                      244                     hardy-madding-crowd
...                                                                           ...
naval-academy-sound-military-decision 560   naval-academy-sound-military-decision
                                      670   naval-academy-sound-military-decision
                                      669   naval-academy-sound-military-decision
                                      668   naval-academy-sound-military-decision
                                      667   naval-academy-sound-military-decision
newsgroup                             1040                              newsgroup
                                      1041                              newsgroup
                                      1042                              newsgroup
                                      1043                              newsgroup
                                      1044                              newsgroup
unamuno-tragic-sense-of-life          1153           unamuno-tragic-sense-of-life
                                      1171           unamuno-tragic-sense-of-life
                                      1172           unamuno-tragic-sense-of-life
                                      1173           unamuno-tragic-sense-of-life
                                      1176           unamuno-tragic-sense-of-life
vaneeden-quest                        1440                         vaneeden-quest
                                      1441                         vaneeden-quest
                                      1442                         vaneeden-quest
                                      1443                         vaneeden-quest
                                      1444                         vaneeden-quest
webster-early-european-history        1200         webster-early-european-history
                                      1237         webster-early-european-history
                                      1238         webster-early-european-history
                                      1240         webster-early-european-history
                                      1242         webster-early-european-history
why-speech-output                     880                       why-speech-output
                                      920                       why-speech-output
                                      921                       why-speech-output
                                      922                       why-speech-output
                                      924                       why-speech-output

                                                                       train_name  \
val_name
beesly-queen-elizabeth                720            unamuno-tragic-sense-of-life
                                      757                 cia-world-factbook-1992
                                      758                 cia-world-factbook-1992
                                      760                    workshop-proceedings
                                      761          webster-early-european-history
cia-world-factbook-1992               320            unamuno-tragic-sense-of-life
                                      1305                                  bible
                                      1306                                  bible
                                      1308                   workshop-proceedings
                                      1309                   workshop-proceedings
eckstein-quintus-claudius             800            unamuno-tragic-sense-of-life
                                      840                    workshop-proceedings
                                      841          webster-early-european-history
                                      842                                   bible
                                      844                                   bible
gallienne-quest-of-golden-girl        433   naval-academy-sound-military-decision
                                      474                 cia-world-factbook-1992
                                      478                 cia-world-factbook-1992
                                      437                 cia-world-factbook-1992
                                      438                 cia-world-factbook-1992
gordon-quiet-talks-crowned-christ     480            unamuno-tragic-sense-of-life
                                      520                    workshop-proceedings
                                      521          webster-early-european-history
                                      522                                   bible
                                      524                                   bible
hardy-madding-crowd                   240            unamuno-tragic-sense-of-life
                                      241                    milton-paradise-lost
                                      242                    milton-paradise-lost
                                      243                     hardy-madding-crowd
                                      244                 cia-world-factbook-1992
...                                                                           ...
naval-academy-sound-military-decision 560            unamuno-tragic-sense-of-life
                                      670          webster-early-european-history
                                      669                    workshop-proceedings
                                      668                    workshop-proceedings
                                      667                 cia-world-factbook-1992
newsgroup                             1040           unamuno-tragic-sense-of-life
                                      1041                   milton-paradise-lost
                                      1042                   milton-paradise-lost
                                      1043                    hardy-madding-crowd
                                      1044                cia-world-factbook-1992
unamuno-tragic-sense-of-life          1153  naval-academy-sound-military-decision
                                      1171                 beesly-queen-elizabeth
                                      1172                cia-world-factbook-1992
                                      1173                                  bible
                                      1176                   workshop-proceedings
vaneeden-quest                        1440           unamuno-tragic-sense-of-life
                                      1441                   milton-paradise-lost
                                      1442                   milton-paradise-lost
                                      1443                    hardy-madding-crowd
                                      1444                cia-world-factbook-1992
webster-early-european-history        1200           unamuno-tragic-sense-of-life
                                      1237                cia-world-factbook-1992
                                      1238                cia-world-factbook-1992
                                      1240                   workshop-proceedings
                                      1242                                  bible
why-speech-output                     880            unamuno-tragic-sense-of-life
                                      920                    workshop-proceedings
                                      921          webster-early-european-history
                                      922                                   bible
                                      924                                   bible

                                            cos_sim  matches
val_name
beesly-queen-elizabeth                720       0.0        0
                                      757       0.0        0
                                      758       0.0        0
                                      760       0.0        0
                                      761       0.0        0
cia-world-factbook-1992               320       0.0        0
                                      1305      0.0        0
                                      1306      0.0        0
                                      1308      0.0        0
                                      1309      0.0        0
eckstein-quintus-claudius             800       0.0        0
                                      840       0.0        0
                                      841       0.0        0
                                      842       0.0        0
                                      844       0.0        0
gallienne-quest-of-golden-girl        433       0.0        0
                                      474       0.0        0
                                      478       0.0        0
                                      437       0.0        0
                                      438       0.0        0
gordon-quiet-talks-crowned-christ     480       0.0        0
                                      520       0.0        0
                                      521       0.0        0
                                      522       0.0        0
                                      524       0.0        0
hardy-madding-crowd                   240       NaN        0
                                      241       NaN        0
                                      242       NaN        0
                                      243       NaN        1
                                      244       NaN        0
...                                             ...      ...
naval-academy-sound-military-decision 560       0.0        0
                                      670       0.0        0
                                      669       0.0        0
                                      668       0.0        0
                                      667       0.0        0
newsgroup                             1040      NaN        0
                                      1041      NaN        0
                                      1042      NaN        0
                                      1043      NaN        0
                                      1044      NaN        0
unamuno-tragic-sense-of-life          1153      0.0        0
                                      1171      0.0        0
                                      1172      0.0        0
                                      1173      0.0        0
                                      1176      0.0        0
vaneeden-quest                        1440      NaN        0
                                      1441      NaN        0
                                      1442      NaN        0
                                      1443      NaN        0
                                      1444      NaN        0
webster-early-european-history        1200      0.0        0
                                      1237      0.0        0
                                      1238      0.0        0
                                      1240      0.0        0
                                      1242      0.0        0
why-speech-output                     880       0.0        0
                                      920       0.0        0
                                      921       0.0        0
                                      922       0.0        0
                                      924       0.0        0

[65 rows x 4 columns]

In [74]:
# k = 25
n = getNeighbors_tfidf(training, val, 25 , 'name')
n_matches = matching(n, 'train_name', 'val_name')
print(listAcc(n_matches, 25))
print('accuracy score:' + str(np.mean(listAcc(n_matches, 25))))
n['matches'] = n_matches
n

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: 'val_name' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version
  app.launch_new_instance()

[0.0, 0.0, 0.0, 0.0, 0.0, 0.04, 0.0, 0.0, 0.04, 0.0, 0.08, 0.0, 0.0]
accuracy score:0.012307692307692308

                                                           val_name  \
val_name
beesly-queen-elizabeth         720           beesly-queen-elizabeth
                               757           beesly-queen-elizabeth
                               758           beesly-queen-elizabeth
                               760           beesly-queen-elizabeth
                               761           beesly-queen-elizabeth
                               762           beesly-queen-elizabeth
                               764           beesly-queen-elizabeth
                               766           beesly-queen-elizabeth
                               767           beesly-queen-elizabeth
                               768           beesly-queen-elizabeth
                               769           beesly-queen-elizabeth
                               772           beesly-queen-elizabeth
                               773           beesly-queen-elizabeth
                               776           beesly-queen-elizabeth
                               777           beesly-queen-elizabeth
                               778           beesly-queen-elizabeth
                               779           beesly-queen-elizabeth
                               786           beesly-queen-elizabeth
                               787           beesly-queen-elizabeth
                               789           beesly-queen-elizabeth
                               790           beesly-queen-elizabeth
                               791           beesly-queen-elizabeth
                               794           beesly-queen-elizabeth
                               795           beesly-queen-elizabeth
                               796           beesly-queen-elizabeth
cia-world-factbook-1992        320          cia-world-factbook-1992
                               1305         cia-world-factbook-1992
                               1306         cia-world-factbook-1992
                               1308         cia-world-factbook-1992
                               1309         cia-world-factbook-1992
...                                                             ...
webster-early-european-history 1270  webster-early-european-history
                               1271  webster-early-european-history
                               1274  webster-early-european-history
                               1275  webster-early-european-history
                               1276  webster-early-european-history
why-speech-output              880                why-speech-output
                               920                why-speech-output
                               921                why-speech-output
                               922                why-speech-output
                               924                why-speech-output
                               925                why-speech-output
                               926                why-speech-output
                               927                why-speech-output
                               928                why-speech-output
                               929                why-speech-output
                               930                why-speech-output
                               931                why-speech-output
                               932                why-speech-output
                               918                why-speech-output
                               933                why-speech-output
                               937                why-speech-output
                               938                why-speech-output
                               939                why-speech-output
                               946                why-speech-output
                               947                why-speech-output
                               949                why-speech-output
                               950                why-speech-output
                               951                why-speech-output
                               954                why-speech-output
                               955                why-speech-output

                                                         train_name  cos_sim  \
val_name
beesly-queen-elizabeth         720     unamuno-tragic-sense-of-life      0.0
                               757          cia-world-factbook-1992      0.0
                               758          cia-world-factbook-1992      0.0
                               760             workshop-proceedings      0.0
                               761   webster-early-european-history      0.0
                               762                            bible      0.0
                               764                            bible      0.0
                               766                            bible      0.0
                               767            selected-polish-tales      0.0
                               768         carroll-alice-wonderland      0.0
                               769   webster-early-european-history      0.0
                               772          cia-world-factbook-1992      0.0
                               773                            bible      0.0
                               776             workshop-proceedings      0.0
                               777            selected-polish-tales      0.0
                               778          cia-world-factbook-1992      0.0
                               779          cia-world-factbook-1992      0.0
                               786                            bible      0.0
                               787   webster-early-european-history      0.0
                               789     unamuno-tragic-sense-of-life      0.0
                               790         carroll-alice-wonderland      0.0
                               791          cia-world-factbook-1992      0.0
                               794          cia-world-factbook-1992      0.0
                               795          cia-world-factbook-1992      0.0
                               796     unamuno-tragic-sense-of-life      0.0
cia-world-factbook-1992        320     unamuno-tragic-sense-of-life      0.0
                               1305                           bible      0.0
                               1306                           bible      0.0
                               1308            workshop-proceedings      0.0
                               1309            workshop-proceedings      0.0
...                                                             ...      ...
webster-early-european-history 1270        carroll-alice-wonderland      0.0
                               1271         cia-world-factbook-1992      0.0
                               1274         cia-world-factbook-1992      0.0
                               1275         cia-world-factbook-1992      0.0
                               1276    unamuno-tragic-sense-of-life      0.0
why-speech-output              880     unamuno-tragic-sense-of-life      0.0
                               920             workshop-proceedings      0.0
                               921   webster-early-european-history      0.0
                               922                            bible      0.0
                               924                            bible      0.0
                               925           beesly-queen-elizabeth      0.0
                               926                            bible      0.0
                               927            selected-polish-tales      0.0
                               928         carroll-alice-wonderland      0.0
                               929   webster-early-european-history      0.0
                               930           beesly-queen-elizabeth      0.0
                               931           beesly-queen-elizabeth      0.0
                               932          cia-world-factbook-1992      0.0
                               918          cia-world-factbook-1992      0.0
                               933                            bible      0.0
                               937            selected-polish-tales      0.0
                               938          cia-world-factbook-1992      0.0
                               939          cia-world-factbook-1992      0.0
                               946                            bible      0.0
                               947   webster-early-european-history      0.0
                               949     unamuno-tragic-sense-of-life      0.0
                               950         carroll-alice-wonderland      0.0
                               951          cia-world-factbook-1992      0.0
                               954          cia-world-factbook-1992      0.0
                               955          cia-world-factbook-1992      0.0

                                     matches
val_name
beesly-queen-elizabeth         720         0
                               757         0
                               758         0
                               760         0
                               761         0
                               762         0
                               764         0
                               766         0
                               767         0
                               768         0
                               769         0
                               772         0
                               773         0
                               776         0
                               777         0
                               778         0
                               779         0
                               786         0
                               787         0
                               789         0
                               790         0
                               791         0
                               794         0
                               795         0
                               796         0
cia-world-factbook-1992        320         0
                               1305        0
                               1306        0
                               1308        0
                               1309        0
...                                      ...
webster-early-european-history 1270        0
                               1271        0
                               1274        0
                               1275        0
                               1276        0
why-speech-output              880         0
                               920         0
                               921         0
                               922         0
                               924         0
                               925         0
                               926         0
                               927         0
                               928         0
                               929         0
                               930         0
                               931         0
                               932         0
                               918         0
                               933         0
                               937         0
                               938         0
                               939         0
                               946         0
                               947         0
                               949         0
                               950         0
                               951         0
                               954         0
                               955         0

[325 rows x 4 columns]

4. Finally, comment your results. How accurate is BOW versus TF-IDF? How does choice of k change
the results? Is BOW or TF-IDF faster to run?

*type your response here*

TF-IDF created more accurate results. There were less 0.0 scores, and the overall scores were higher 
Increasing the choice of k increases the score, probably because the language in each text is not similar.
Bow is faster to run because there are less matrix operations

# Are tomatoes fresh or rotten?

Our next task is to use your freshly minted methods for classifying the Rotten Tomatoes movie reviews.
Please familiarize yourself a little bit with the webpage. Briefly, approved critics can write reviews for
movies, and evaluate the movie as fresh or rotten. The webpage normally shows a short quote from
each critic, and whether it was evaluated as fresh or rotten. You will work on these quotes below.
The central variables in rotten-tomatoes.csv are the following:
critic name of the critic
fresh evaluation: 'fresh' or 'rotten'
quote short version of the review
review_date when the review was written.
There are more variables like links to IMDB.
1. Load the data. Inspect it a little bit to see how it is coded and organized. How many cases do you
have?
2. Clean the data. Retain only cases where fresh and quote are present and non-empty. Remove
repeated observations (there are such in data). How many cases will be left?

In [5]:
#load data
tomatoes = pd.read_csv("rotten-tomatoes.csv.gz")

#explore data
print("rows in original data: " + str(len(tomatoes)))
print(tomatoes.isnull().sum())

#clean data
tomatoes = tomatoes.drop_duplicates()
print("rows after duplicates dropped: " + str(len(tomatoes)))

tomatoes = tomatoes.loc[tomatoes.fresh != "none"]
print("rows after fresh 'none' values dropped: " + str(len(tomatoes)))

rows in original data: 13442
critic         705
fresh            0
imdb             0
link             0
publication      0
quote            0
review_date      0
rtid             0
title            0
dtype: int64
rows after duplicates dropped: 12846
rows after fresh 'none' values dropped: 12823

3. Select training and validation data. You would like to split all cases into 80-20 groups. However, as before, this may be slow. Start slow with perhaps 100 random quotes split into two groups.

In [6]:
#choose 100 random rows from tomatoes
num = 100
ntom = tomatoes.sample(num, random_state = 2).reset_index()

#split into train and test
training = ntom.head(int(num * 0.8))
val = ntom.tail(int(num * 0.2))

4. Your task is to find the closest training quotes for each test quote, and based on those predict if the
movie is fresh or rotten according to the quote.
Follow the same steps you did with the texts above:

(a) create dictionary and BOW of all quotes

(b) run k-NN with several different k-s, and predict if fresh or rotten. In each time compute the
accuracy.

(c) transform your data into TF-IDF form and repeat k-NN.

In [7]:
#creating dictionary for tomatoes
vec_fit = vectorizer.fit(ntom.quote)

In [20]:
def getNN(training, validation, k, test):
    freq_table = pd.DataFrame(columns=['val_fresh', 'train_fresh', 'cos_sim', 'v_index',
                                      't_index'])
    X = vec_fit.transform(training[test]).toarray()
    y = vec_fit.transform(validation[test]).toarray()
    for i in range(0, len(y)):
        ft = {'val_fresh' : [] , 'train_fresh' : [], 'cos_sim' : [],
                 'v_index' : [], 't_index' : []}
        for j in range(0, len(X)):
            ft['val_fresh'].append(validation.iloc[i]['fresh'])
            ft['train_fresh'].append(training.iloc[j]['fresh'])
            ft['cos_sim'].append(cos_sim(y[i, ], X[j, ]))
            ft['v_index'].append(validation.iloc[i]['index'])
            ft['t_index'].append(training.iloc[j]['index'])
        ft = pd.DataFrame(data = ft)
        ft = ft.nsmallest(k, 'cos_sim')
        freq_table = freq_table.append(ft)
    return freq_table

In [32]:
def matching(df, col1, col2):
    matches = []
    for i in range(0, len(df)):
        if df.iloc[i][col1] == df.iloc[i][col2]:
            matches.append(1)
        else:
            matches.append(0)
    return matches

In [35]:
def listAcc(matches, k):
    accuracies = []
    i = 0
    while i < len(matches):
        ival = np.mean(matches[i : i+k])
        accuracies.append(np.mean(ival))
        i = i + k
    return accuracies

In [36]:
n1 = getNN(training, val, 1 , 'quote')
n1_matches = matching(n1, 'train_fresh', 'val_fresh')
print(listAcc(n1_matches, 1))
print('accuracy score:' + str(np.mean(listAcc(n1_matches, 1))))

[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
accuracy score:0.3

In [38]:
n1['matches'] = n1_matches
n1

   val_fresh train_fresh  cos_sim v_index t_index  matches
15     fresh      rotten      0.0    7784    6074        0
15     fresh      rotten      0.0    6288    6074        0
15     fresh      rotten      0.0    6901    6074        0
18    rotten       fresh      0.0    2682    6972        0
1      fresh      rotten      0.0    1701    7218        0
1     rotten      rotten      0.0     871    7218        1
11    rotten      rotten      0.0    3928    8958        1
0     rotten       fresh      0.0   10142    3999        0
5      fresh      rotten      0.0    7850    9469        0
1      fresh      rotten      0.0   12128    7218        0
0      fresh       fresh      0.0    9825    3999        1
1      fresh      rotten      0.0    3579    7218        0
1     rotten      rotten      0.0    1283    7218        1
6      fresh       fresh      0.0    8363    2875        1
1      fresh      rotten      0.0   10920    7218        0
6     rotten       fresh      0.0   10276    2875        0
15     fresh      rotten      0.0    7778    6074        0
1      fresh      rotten      0.0   13237    7218        0
8     rotten       fresh      0.0    2569    4022        0
6      fresh       fresh      0.0     759    2875        1

In [40]:
n2 = getNN(training, val, 5 , 'quote')
n2_matches = matching(n2, 'train_fresh', 'val_fresh')
print(listAcc(n2_matches, 5))
print('accuracy score:' + str(np.mean(listAcc(n2_matches, 5))))
n2['matches'] = n2_matches
n2

[0.6, 0.4, 0.4, 0.4, 0.4, 0.4, 0.6, 0.8, 0.4, 0.4, 0.8, 0.6, 0.6, 0.6, 0.4, 0.2, 0.4, 0.4, 0.2, 0.4]
accuracy score:0.47000000000000003

In [46]:
n3 = getNN(training, val, 25 , 'quote')
n3_matches = matching(n3, 'train_fresh', 'val_fresh')
print(listAcc(n3_matches, 25))
print('accuracy score:' + str(np.mean(listAcc(n3_matches, 25))))
n3['matches'] = n3_matches
n3

[0.64, 0.52, 0.6, 0.36, 0.52, 0.28, 0.44, 0.52, 0.64, 0.44, 0.52, 0.68, 0.44, 0.56, 0.56, 0.36, 0.68, 0.48, 0.24, 0.6]
accuracy score:0.504

   val_fresh train_fresh   cos_sim v_index t_index  matches
15     fresh      rotten  0.000000    7784    6074        0
18     fresh       fresh  0.000000    7784    6972        1
21     fresh       fresh  0.000000    7784     584        1
22     fresh      rotten  0.000000    7784    1056        0
34     fresh       fresh  0.000000    7784     597        1
36     fresh       fresh  0.000000    7784    3261        1
44     fresh      rotten  0.000000    7784   11416        0
50     fresh      rotten  0.000000    7784    1244        0
56     fresh       fresh  0.000000    7784    4984        1
62     fresh       fresh  0.000000    7784    6425        1
63     fresh      rotten  0.000000    7784    6711        0
65     fresh       fresh  0.000000    7784   13172        1
69     fresh      rotten  0.000000    7784   11065        0
70     fresh       fresh  0.000000    7784   10913        1
24     fresh       fresh  0.042796    7784    5224        1
60     fresh       fresh  0.047219    7784    3337        1
1      fresh      rotten  0.056614    7784    7218        0
13     fresh       fresh  0.069338    7784    1157        1
8      fresh       fresh  0.074125    7784    4022        1
77     fresh       fresh  0.076923    7784    4994        1
6      fresh       fresh  0.078446    7784    2875        1
47     fresh       fresh  0.092450    7784    1439        1
26     fresh       fresh  0.098058    7784    1570        1
79     fresh      rotten  0.098058    7784    6564        0
11     fresh      rotten  0.104828    7784    8958        0
15     fresh      rotten  0.000000    6288    6074        0
18     fresh       fresh  0.000000    6288    6972        1
63     fresh      rotten  0.000000    6288    6711        0
24     fresh       fresh  0.034080    6288    5224        1
22     fresh      rotten  0.036811    6288    1056        0
..       ...         ...       ...     ...     ...      ...
17    rotten      rotten  0.098295    2569   11518        1
36    rotten       fresh  0.111111    2569    3261        0
47    rotten       fresh  0.111111    2569    1439        0
26    rotten       fresh  0.117851    2569    1570        0
68    rotten       fresh  0.125988    2569    3137        0
6      fresh       fresh  0.000000     759    2875        1
15     fresh      rotten  0.000000     759    6074        0
18     fresh       fresh  0.000000     759    6972        1
20     fresh      rotten  0.000000     759    7079        0
22     fresh      rotten  0.000000     759    1056        0
34     fresh       fresh  0.000000     759     597        1
44     fresh      rotten  0.000000     759   11416        0
50     fresh      rotten  0.000000     759    1244        0
63     fresh      rotten  0.000000     759    6711        0
65     fresh       fresh  0.000000     759   13172        1
69     fresh      rotten  0.000000     759   11065        0
36     fresh       fresh  0.038236     759    3261        1
1      fresh      rotten  0.046829     759    7218        0
56     fresh       fresh  0.054074     759    4984        1
66     fresh       fresh  0.054074     759     813        1
26     fresh       fresh  0.081111     759    1570        1
59     fresh       fresh  0.087407     759    2069        1
30     fresh       fresh  0.111648     759    8696        1
74     fresh       fresh  0.111648     759    8973        1
47     fresh       fresh  0.114708     759    1439        1
64     fresh      rotten  0.114708     759    2926        0
70     fresh       fresh  0.114708     759   10913        1
3      fresh       fresh  0.118470     759    4317        1
4      fresh       fresh  0.118470     759   10067        1
40     fresh      rotten  0.120495     759    8588        0

[500 rows x 6 columns]

In [42]:
#TF-IDF
def getNN_tfidf(training, validation, k, test):
    freq_table = pd.DataFrame(columns=['val_fresh', 'train_fresh', 'cos_sim', 'v_index',
                                      't_index'])
    X = vec_fit.transform(training[test]).toarray()
    y = vec_fit.transform(validation[test]).toarray()
    
    X = tf(X) * idf(X)
    y = tf(y) * idf(y)
    
    for i in range(0, len(y)):
        ft = {'val_fresh' : [] , 'train_fresh' : [], 'cos_sim' : [],
                 'v_index' : [], 't_index' : []}
        for j in range(0, len(X)):
            ft['val_fresh'].append(validation.iloc[i]['fresh'])
            ft['train_fresh'].append(training.iloc[j]['fresh'])
            ft['cos_sim'].append(cos_sim(y[i, ], X[j, ]))
            ft['v_index'].append(validation.iloc[i]['index'])
            ft['t_index'].append(training.iloc[j]['index'])
        ft = pd.DataFrame(data = ft)
        ft = ft.nsmallest(k, 'cos_sim')
        freq_table = freq_table.append(ft)
    return freq_table

In [43]:
#k = 1
n4 = getNN(training, val, 1 , 'quote')
n4_matches = matching(n4, 'train_fresh', 'val_fresh')
print(listAcc(n4_matches, 1))
print('accuracy score:' + str(np.mean(listAcc(n4_matches, 1))))
n4['matches'] = n4_matches
n4

[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
accuracy score:0.3

   val_fresh train_fresh  cos_sim v_index t_index  matches
15     fresh      rotten      0.0    7784    6074        0
15     fresh      rotten      0.0    6288    6074        0
15     fresh      rotten      0.0    6901    6074        0
18    rotten       fresh      0.0    2682    6972        0
1      fresh      rotten      0.0    1701    7218        0
1     rotten      rotten      0.0     871    7218        1
11    rotten      rotten      0.0    3928    8958        1
0     rotten       fresh      0.0   10142    3999        0
5      fresh      rotten      0.0    7850    9469        0
1      fresh      rotten      0.0   12128    7218        0
0      fresh       fresh      0.0    9825    3999        1
1      fresh      rotten      0.0    3579    7218        0
1     rotten      rotten      0.0    1283    7218        1
6      fresh       fresh      0.0    8363    2875        1
1      fresh      rotten      0.0   10920    7218        0
6     rotten       fresh      0.0   10276    2875        0
15     fresh      rotten      0.0    7778    6074        0
1      fresh      rotten      0.0   13237    7218        0
8     rotten       fresh      0.0    2569    4022        0
6      fresh       fresh      0.0     759    2875        1

In [44]:
#k = 5
n5 = getNN(training, val, 5 , 'quote')
n5_matches = matching(n5, 'train_fresh', 'val_fresh')
print(listAcc(n5_matches, 5))
print('accuracy score:' + str(np.mean(listAcc(n5_matches, 5))))
n5['matches'] = n5_matches
n5

[0.6, 0.4, 0.4, 0.4, 0.4, 0.4, 0.6, 0.8, 0.4, 0.4, 0.8, 0.6, 0.6, 0.6, 0.4, 0.2, 0.4, 0.4, 0.2, 0.4]
accuracy score:0.47000000000000003

   val_fresh train_fresh   cos_sim v_index t_index  matches
15     fresh      rotten  0.000000    7784    6074        0
18     fresh       fresh  0.000000    7784    6972        1
21     fresh       fresh  0.000000    7784     584        1
22     fresh      rotten  0.000000    7784    1056        0
34     fresh       fresh  0.000000    7784     597        1
15     fresh      rotten  0.000000    6288    6074        0
18     fresh       fresh  0.000000    6288    6972        1
63     fresh      rotten  0.000000    6288    6711        0
24     fresh       fresh  0.034080    6288    5224        1
22     fresh      rotten  0.036811    6288    1056        0
15     fresh      rotten  0.000000    6901    6074        0
18     fresh       fresh  0.000000    6901    6972        1
34     fresh       fresh  0.000000    6901     597        1
44     fresh      rotten  0.000000    6901   11416        0
50     fresh      rotten  0.000000    6901    1244        0
18    rotten       fresh  0.000000    2682    6972        0
22    rotten      rotten  0.000000    2682    1056        1
24    rotten       fresh  0.000000    2682    5224        0
50    rotten      rotten  0.000000    2682    1244        1
56    rotten       fresh  0.000000    2682    4984        0
1      fresh      rotten  0.000000    1701    7218        0
6      fresh       fresh  0.000000    1701    2875        1
15     fresh      rotten  0.000000    1701    6074        0
18     fresh       fresh  0.000000    1701    6972        1
20     fresh      rotten  0.000000    1701    7079        0
1     rotten      rotten  0.000000     871    7218        1
2     rotten       fresh  0.000000     871    5818        0
3     rotten       fresh  0.000000     871    4317        0
4     rotten       fresh  0.000000     871   10067        0
9     rotten      rotten  0.000000     871   10814        1
..       ...         ...       ...     ...     ...      ...
1      fresh      rotten  0.000000   10920    7218        0
6      fresh       fresh  0.000000   10920    2875        1
15     fresh      rotten  0.000000   10920    6074        0
18     fresh       fresh  0.000000   10920    6972        1
22     fresh      rotten  0.000000   10920    1056        0
6     rotten       fresh  0.000000   10276    2875        0
8     rotten       fresh  0.000000   10276    4022        0
15    rotten      rotten  0.000000   10276    6074        1
18    rotten       fresh  0.000000   10276    6972        0
34    rotten       fresh  0.000000   10276     597        0
15     fresh      rotten  0.000000    7778    6074        0
18     fresh       fresh  0.000000    7778    6972        1
34     fresh       fresh  0.000000    7778     597        1
50     fresh      rotten  0.000000    7778    1244        0
63     fresh      rotten  0.000000    7778    6711        0
1      fresh      rotten  0.000000   13237    7218        0
15     fresh      rotten  0.000000   13237    6074        0
18     fresh       fresh  0.000000   13237    6972        1
22     fresh      rotten  0.000000   13237    1056        0
26     fresh       fresh  0.000000   13237    1570        1
8     rotten       fresh  0.000000    2569    4022        0
15    rotten      rotten  0.000000    2569    6074        1
18    rotten       fresh  0.000000    2569    6972        0
21    rotten       fresh  0.000000    2569     584        0
34    rotten       fresh  0.000000    2569     597        0
6      fresh       fresh  0.000000     759    2875        1
15     fresh      rotten  0.000000     759    6074        0
18     fresh       fresh  0.000000     759    6972        1
20     fresh      rotten  0.000000     759    7079        0
22     fresh      rotten  0.000000     759    1056        0

[100 rows x 6 columns]

In [45]:
# k = 25
n6 = getNN(training, val, 25 , 'quote')
n6_matches = matching(n6, 'train_fresh', 'val_fresh')
print(listAcc(n6_matches, 25))
print('accuracy score:' + str(np.mean(listAcc(n6_matches,25))))
n6['matches'] = n6_matches
n6

[0.64, 0.52, 0.6, 0.36, 0.52, 0.28, 0.44, 0.52, 0.64, 0.44, 0.52, 0.68, 0.44, 0.56, 0.56, 0.36, 0.68, 0.48, 0.24, 0.6]
accuracy score:0.504

   val_fresh train_fresh   cos_sim v_index t_index  matches
15     fresh      rotten  0.000000    7784    6074        0
18     fresh       fresh  0.000000    7784    6972        1
21     fresh       fresh  0.000000    7784     584        1
22     fresh      rotten  0.000000    7784    1056        0
34     fresh       fresh  0.000000    7784     597        1
36     fresh       fresh  0.000000    7784    3261        1
44     fresh      rotten  0.000000    7784   11416        0
50     fresh      rotten  0.000000    7784    1244        0
56     fresh       fresh  0.000000    7784    4984        1
62     fresh       fresh  0.000000    7784    6425        1
63     fresh      rotten  0.000000    7784    6711        0
65     fresh       fresh  0.000000    7784   13172        1
69     fresh      rotten  0.000000    7784   11065        0
70     fresh       fresh  0.000000    7784   10913        1
24     fresh       fresh  0.042796    7784    5224        1
60     fresh       fresh  0.047219    7784    3337        1
1      fresh      rotten  0.056614    7784    7218        0
13     fresh       fresh  0.069338    7784    1157        1
8      fresh       fresh  0.074125    7784    4022        1
77     fresh       fresh  0.076923    7784    4994        1
6      fresh       fresh  0.078446    7784    2875        1
47     fresh       fresh  0.092450    7784    1439        1
26     fresh       fresh  0.098058    7784    1570        1
79     fresh      rotten  0.098058    7784    6564        0
11     fresh      rotten  0.104828    7784    8958        0
15     fresh      rotten  0.000000    6288    6074        0
18     fresh       fresh  0.000000    6288    6972        1
63     fresh      rotten  0.000000    6288    6711        0
24     fresh       fresh  0.034080    6288    5224        1
22     fresh      rotten  0.036811    6288    1056        0
..       ...         ...       ...     ...     ...      ...
17    rotten      rotten  0.098295    2569   11518        1
36    rotten       fresh  0.111111    2569    3261        0
47    rotten       fresh  0.111111    2569    1439        0
26    rotten       fresh  0.117851    2569    1570        0
68    rotten       fresh  0.125988    2569    3137        0
6      fresh       fresh  0.000000     759    2875        1
15     fresh      rotten  0.000000     759    6074        0
18     fresh       fresh  0.000000     759    6972        1
20     fresh      rotten  0.000000     759    7079        0
22     fresh      rotten  0.000000     759    1056        0
34     fresh       fresh  0.000000     759     597        1
44     fresh      rotten  0.000000     759   11416        0
50     fresh      rotten  0.000000     759    1244        0
63     fresh      rotten  0.000000     759    6711        0
65     fresh       fresh  0.000000     759   13172        1
69     fresh      rotten  0.000000     759   11065        0
36     fresh       fresh  0.038236     759    3261        1
1      fresh      rotten  0.046829     759    7218        0
56     fresh       fresh  0.054074     759    4984        1
66     fresh       fresh  0.054074     759     813        1
26     fresh       fresh  0.081111     759    1570        1
59     fresh       fresh  0.087407     759    2069        1
30     fresh       fresh  0.111648     759    8696        1
74     fresh       fresh  0.111648     759    8973        1
47     fresh       fresh  0.114708     759    1439        1
64     fresh      rotten  0.114708     759    2926        0
70     fresh       fresh  0.114708     759   10913        1
3      fresh       fresh  0.118470     759    4317        1
4      fresh       fresh  0.118470     759   10067        1
40     fresh      rotten  0.120495     759    8588        0

[500 rows x 6 columns]

(d) inspect a few cases where the tomato was correctly/incorrectly predicted. Can you explain why
the algorithm behaved in the way it behaved?

*comment your results here*

It seems like quotes with unequal lengths seemed to be incorrectly predicted and cases with similar words and lengths were more correctly predicted.

5. Finally, comment your results. What worked better: reviews or text pages? What worked better:
BOW or TF-IDF?

*comment your results here*

The reviews worked better, and the TF_IDF worked better.